apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  # namespace: dev
spec:
  replicas: 6
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
      nodeName: my-cluster-worker
